import { createClient } from '@/lib/supabase/server';
import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get('code');
  const next = searchParams.get('next') ?? '/dashboard';

  if (code) {
    const supabase = await createClient();
    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      const forwardedHost = request.headers.get('x-forwarded-host');
      const isLocalEnv = process.env.NODE_ENV === 'development';

      if (isLocalEnv) {
        return NextResponse.redirect(`${origin}${next}`);
      } else if (forwardedHost) {
        return NextResponse.redirect(`https://${forwardedHost}${next}`);
      } else {
        return NextResponse.redirect(`${origin}${next}`);
      }
    }
  }

  // Handle implicit flow (hash fragment) - Usually handled client side but we can redirect to a client page that handles it
  // Since this is a server route, we can't see the hash. The user said they are redirected to THIS route with a hash.
  // We need to serve a page that can parse the hash.
  // Actually, usually magic links from generateLink contain a 'code' query param if configured as such, 
  // OR they are a direct link to the app which then parses hash.
  // The link generated by admin.generateLink might be returning a hash-based URL which is meant to be handled by the client.

  // Return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/?error=auth`);
}
